
# general options
src_lang: en
target_lang: vi

# model
d_model: 512
num_layers: 6
num_heads: 8
d_ffn: 2048
dropout_rate: 0.1
attention_dropout_rate: 0.1

# optimization
learning_rate: 0.4
enable_lr_scheduler: True
warmup_steps: 4000
label_smoothing: 0.1
max_grad_norm: 1.0
beam_size: 5

# dataset (hugging face)
dataset_path: mt_eng_vietnamese
dataset_name: iwslt2015-en-vi

# training
preload: null
batch_size: 32
num_epochs: 10
num_validation_samples: 200
num_test_samples: -1
seq_length: 120
