checkpoint: /path/to/checkpoint.pt
src_tokenizer: /path/to/source_tokenizer.json
target_tokenizer: /path/to/target_tokenizer.json

seq_length: 120
beam_size: 4
beam_return_topk: 3
preprocess:
  lowercase: true
  contractions: true
postprocess:
  remove_underscores: true
